development:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_development
  pool: 20
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_test
  pool: 20
  host: localhost
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_production
  pool: 20
  host: localhost
  password: