development:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_development
  pool: 2
  host: localhost
  username:  AdiSingh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_test
  pool: 2
  host: localhost
  username:  AdiSingh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_production
  pool: 2
  host: localhost
  username:  AdiSingh
  password: