development:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_development
  host: localhost
  username: AdiSingh
  pool: 20
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nightfalls_test
  host: localhost
  username: AdiSingh
  pool: 20
  password: